import store from "./store";
import {
  resetWaliSantriState,
  setNamaLengkapWali,
  setNoTelepon,
  setHubunganDenganSantri,
  setAlamatWali,
  setGambarWali,
  resetAuthState,
  setUsername,
  setPassword,
  setGambarUser,
  setRole,
  resetSantriState,
  setAlamat,
  setIdWali,
  setJenisKelamin,
  setNamaLengkap,
  setTanggalLahir,
  setTempatLahir,
  setGambarSantri,
} from "./slices";

export {
  store,
  resetWaliSantriState,
  setNamaLengkapWali,
  setNoTelepon,
  setHubunganDenganSantri,
  setAlamatWali,
  setGambarWali,
  resetAuthState,
  setUsername,
  setPassword,
  setGambarUser,
  setRole,
  resetSantriState,
  setAlamat,
  setIdWali,
  setJenisKelamin,
  setNamaLengkap,
  setTanggalLahir,
  setTempatLahir,
  setGambarSantri,
};