import store from "./store";
import {
  resetWaliSantriState,
  setNamaLengkapWali,
  setNoTelepon,
  setHubunganDenganSantri,
  setAlamatWali,
  setGambarWali,
  resetAuthState,
  setUsername,
  setPassword,
  setGambarUser,
  setRole,
  resetSantriState,
  setAlamat,
  setIdWali,
  setJenisKelamin,
  setNamaLengkap,
  setTanggalLahir,
  setTempatLahir,
  setGambarSantri,
  resetPengajarState,
  setGambarPengajar,
  setNamaLengkapPengajar,
  setSpesialisasi,
  setAlamatPengajar,
  setNoTeleponPengajar,
  setNilai,
  setKeterangan,
  setTanggalPenilaian,
  setIdSantri,
  setIdJadwal,
  resetNilaiSantriState,

  // ✅ Tambahan dari jadwalPengajaranSlice
  resetJadwalPengajaran,
  setHari,
  setMataPelajaran,
  setJamMulai,
  setJamSelesai,
  setIdPengajar,
} from "./slices";

export {
  store,
  resetWaliSantriState,
  setNamaLengkapWali,
  setNoTelepon,
  setHubunganDenganSantri,
  setAlamatWali,
  setGambarWali,
  resetAuthState,
  setUsername,
  setPassword,
  setGambarUser,
  setRole,
  resetSantriState,
  setAlamat,
  setIdWali,
  setJenisKelamin,
  setNamaLengkap,
  setTanggalLahir,
  setTempatLahir,
  setGambarSantri,
  resetPengajarState,
  setGambarPengajar,
  setNamaLengkapPengajar,
  setSpesialisasi,
  setAlamatPengajar,
  setNoTeleponPengajar,
  setNilai,
  setKeterangan,
  setTanggalPenilaian,
  setIdSantri,
  setIdJadwal,
  resetNilaiSantriState,

  // ✅ Export tambahan untuk jadwal pengajaran
  resetJadwalPengajaran,
  setHari,
  setMataPelajaran,
  setJamMulai,
  setJamSelesai,
  setIdPengajar,
};
